account/urls.py
from django.urls import path, include
from .views import index, django_signup, django_login
from django.conf.urls import url

app_name = 'djangoaccounts'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', django_signup, name='signup'),
    path('login/', django_login, name='login'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import cartList, createCart, addItemQty, deleteItemQty

app_name = 'cart'

urlpatterns = [
    path('cartList', cartList, name='cartList'),
    path('createCart', createCart, name='createCart'),
    path('addItemQty', addItemQty, name='addItemQty'),
    path('deleteItemQty', deleteItemQty, name='deleteItemQty')
]

checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('process/', views.process, name="process"),
    path("submit/", views.submit, name="submit")
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import landing, product_detail

app_name = 'dashboard'

urlpatterns = [
    path('', landing, name='landing'),
    path('product/<slug:slug>/<int:index>', product_detail, name='product_detail')
]

transactions/urls.py
from django.urls import path
from . import views

app_name = "transactions"

urlpatterns = [
    path("history/", views.history_view, name="history"),
    path("checkout/", views.checkout, name="checkout"),
    path("add_transaction/", views.add_transaction, name="add")
]

wartec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'), name='dashboard'),
    path('', include('cart.urls'), name='cart'),
    path('accounts/', include('allauth.urls')),
    path('accountLogin/', TemplateView.as_view(template_name='social_app/socialindex.html'), name='social_app'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("checkout/", include("checkout.urls"),name="checkout"),
    path('coupon/', include('coupon.urls'), name="coupon"),
    path("transactions/",include("transactions.urls"), name="transactions"),   
    path('djangoaccounts/', include('account.urls'), name='djangoaccounts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %} {% load l10n %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta Link for JS -->
    <meta name="createCartMeta" content="{% url 'cart:createCart' %}">
    <meta name="addItemQtyCartMeta" content="{% url 'cart:addItemQty' %}">
    <meta name="deleteItemQtyCartMeta" content="{% url 'cart:deleteItemQty' %}">
    <meta name="cartListCartMeta" content="{% url 'cart:cartList' %}">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

    <!-- Google Fonts API -->
    <link href="https://fonts.googleapis.com/css?family=Share+Tech&display=swap" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <!-- Title -->
    <title>Welcome to Wartec</title>
</head>

<body class="light">

    <!-- Cart Modal -->
    {% include 'cart/modal.html' %}

    <!-- Navbar -->
    {% block navbar %}
    <div class="navContainer">
        <div class="navLogo">Wartec</div>
        <div class="navLink">
            <a href="{% url 'dashboard:landing'%}">
                <div>
                    <div class="navLinkLogo">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M10 20V14H14V20H19V12H22L12 3L2 12H5V20H10Z" fill="black"/>
                        </svg>
                    </div>
                    <p>Home</p>
                </div>
            </a>
            <a href="{% url 'checkout:submit'%}">
                <div>

                    <div class="navLinkLogo">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11.8001 10.9C9.53007 10.31 8.80007 9.7 8.80007 8.75C8.80007 7.66 9.81007 6.9 11.5001 6.9C13.2801 6.9 13.9401 7.75 14.0001 9H16.2101C16.1401 7.28 15.0901 5.7 13.0001 5.19V3H10.0001V5.16C8.06007 5.58 6.50007 6.84 6.50007 8.77C6.50007 11.08 8.41007 12.23 11.2001 12.9C13.7001 13.5 14.2001 14.38 14.2001 15.31C14.2001 16 13.7101 17.1 11.5001 17.1C9.44007 17.1 8.63007 16.18 8.52007 15H6.32007C6.44007 17.19 8.08007 18.42 10.0001 18.83V21H13.0001V18.85C14.9501 18.48 16.5001 17.35 16.5001 15.3C16.5001 12.46 14.0701 11.49 11.8001 10.9Z" fill="black"/>
                        </svg>
                    </div>
                    <p>Checkout</p>
                </div>
            </a>

            <a href="{% url 'transactions:history'%}">
                <div>
                    <div class="navLinkLogo">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13 3C8.03 3 4 7.03 4 12H1L4.89 15.89L4.96 16.03L9 12H6C6 8.13 9.13 5 13 5C16.87 5 20 8.13 20 12C20 15.87 16.87 19 13 19C11.07 19 9.32 18.21 8.06 16.94L6.64 18.36C8.27 19.99 10.51 21 13 21C17.97 21 22 16.97 22 12C22 7.03 17.97 3 13 3ZM12 8V13L16.28 15.54L17 14.33L13.5 12.25V8H12Z" fill="black"/>
                        </svg>
                    </div>
                    <p>History</p>
                </div>
            </a>
            {% if user.is_authenticated %}
            <a class="showCart">
                <div>
                    <div class="navLinkLogo">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M7 18C5.9 18 5.01 18.9 5.01 20C5.01 21.1 5.9 22 7 22C8.1 22 9 21.1 9 20C9 18.9 8.1 18 7 18ZM1 2V4H3L6.6 11.59L5.25 14.04C5.09 14.32 5 14.65 5 15C5 16.1 5.9 17 7 17H19V15H7.42C7.28 15 7.17 14.89 7.17 14.75L7.2 14.63L8.1 13H15.55C16.3 13 16.96 12.59 17.3 11.97L20.88 5.48C20.96 5.34 21 5.17 21 5C21 4.45 20.55 4 20 4H5.21L4.27 2H1ZM17 18C15.9 18 15.01 18.9 15.01 20C15.01 21.1 15.9 22 17 22C18.1 22 19 21.1 19 20C19 18.9 18.1 18 17 18Z" fill="#27AE60"/>
                            </svg>
                    </div>
                    <p class="showCartNav">My Cart</p>
                </div>
            </a> {%else%}
            <a href="{% url 'djangoaccounts:index'%}">
                <div>
                    <div class="navLinkLogo">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9 11.75C8.31 11.75 7.75 12.31 7.75 13C7.75 13.69 8.31 14.25 9 14.25C9.69 14.25 10.25 13.69 10.25 13C10.25 12.31 9.69 11.75 9 11.75ZM15 11.75C14.31 11.75 13.75 12.31 13.75 13C13.75 13.69 14.31 14.25 15 14.25C15.69 14.25 16.25 13.69 16.25 13C16.25 12.31 15.69 11.75 15 11.75ZM12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM12 20C7.59 20 4 16.41 4 12C4 11.71 4.02 11.42 4.05 11.14C6.41 10.09 8.28 8.16 9.26 5.77C11.07 8.33 14.05 10 17.42 10C18.2 10 18.95 9.91 19.67 9.74C19.88 10.45 20 11.21 20 12C20 16.41 16.41 20 12 20Z" fill="black"/>
                            </svg>
                    </div>
                    <p>Login</p>
                </div>
            </a>

            {%endif%}
        </div>
    </div>
    {% endblock %}

    <!-- Contents from different html files, please extends the base.html -->
    {% block content %} {% endblock %}

    <!-- Our JS -->
    <script src=" {% static 'js/cart.js'%} " type="text/javascript "></script>
    <script src=" {% static 'js/dashboard.js'%} " type="text/javascript "></script>
    <script src=" {% static 'js/checkout.js'%} " type="text/javascript "></script>

    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>