account/urls.py
from django.urls import path, include
from .views import index, django_signup, django_login
from django.conf.urls import url

app_name = 'djangoaccounts'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', django_signup, name='signup'),
    path('login/', django_login, name='login'),
]

cart/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import cartList, createCart, addItemQty, deleteItemQty

app_name = 'cart'

urlpatterns = [
    path('cartList', cartList, name='cartList'),
    path('createCart', createCart, name='createCart'),
    path('addItemQty', addItemQty, name='addItemQty'),
    path('deleteItemQty', deleteItemQty, name='deleteItemQty')
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import landing, product_detail

app_name = 'dashboard'

urlpatterns = [
    path('', landing, name='landing'),
    path('product/<slug:slug>/<int:index>', product_detail, name='product_detail')
]

wartec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'), name='dashboard'),
    path('', include('cart.urls'), name='cart'),
    path('accounts/', include('allauth.urls')),
    path('accountLogin/', TemplateView.as_view(template_name='social_app/socialindex.html'), name='social_app'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("checkout/", include("checkout.urls"),name="checkout"),
    path('coupon/', include('coupon.urls'), name="coupon"),
    path("transactions/",include("transactions.urls"), name="transactions"),   
    path('djangoaccounts/', include('account.urls'), name='djangoaccounts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/users/djaccindex.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>Are you new here?</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:landing'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}

            <a class="cta-white btn" href="{% url 'djangoaccounts:signup' %}">Yes I am</a>
            <a class="cta-white btn" href="{% url 'djangoaccounts:login' %}">No, I have an account</a>{% endif %}
        </div>
    </section>

</body>

</html>

templates/users/djacclogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account Login</title>
</head>

<body>

    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>May I ask who you are?</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h2 class="welcome">Welcome back, {{ user.username }} !</h2>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:landing'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}

            <form class="flexrow-llcl" action="{% url 'djangoaccounts:login' %}" method="post">
                {% csrf_token %} {% if form != None %} {{loginform}} {% else %}
                <br>
                <label for="username">Username: </label>
                <input id="id_username" type="text" name="username" placeholder="Unique username" value="{{ username }}" required>
                <label for="password">Password: </label>
                <input id="id_password" type="password" name="password" placeholder="Classified password" value="{{ password }}" required> {% endif %}
                <input type="submit" class="loginbtn cta-white btn" value="Login!">

            </form>
            <a href="/djangoaccounts/signup">
                <p>Sign Up!</p>{% endif %}
        </div>
    </section>
</body>

</html>

templates/users/djaccsignup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Django Account Registration</title>
</head>

<body>
    <section class="container-100vh flexrow-ccc">
        <div class="flexrow-ccc">
            <div class="title">
                <h1>How may I address you?</h1>
            </div>
            <br> {% if user.is_authenticated %}
            <h1 class="welcome">Welcome back, {{ user.username }} !</h1>
            <p>You've succesfully login via Django</p>
            <a class="cta-white btn" href="{% url 'dashboard:dashboard'%}">Redirect to Dashboard!</a>
            <a class="logoutbtn btn" href="{% url 'logout'%}">logout</a> {% else %}
            

            <form class="flexrow-llcl" action="/djangoaccounts/signup/" method="post">
                {% csrf_token %} {% for field in signupform %}
                <h5>{{ field.label_tag }}</h5>
                <p>{{ field }}</p>
                {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small><br> {% endif %}{% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %} <br>{% endfor %}
                <input type="submit" class="createaccount cta-green btn" value="Create Account!">

            </form>
            <a href="/djangoaccounts/login/">
                <p>Already have one?</p>
            </a>
            {% endif %}
        </div>
    </section>

</body>

</html>