cart/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import cartList, createCart, addItemQty, deleteItemQty

app_name = 'cart'

urlpatterns = [
    path('cartList', cartList, name='cartList'),
    path('createCart', createCart, name='createCart'),
    path('addItemQty', addItemQty, name='addItemQty'),
    path('deleteItemQty', deleteItemQty, name='deleteItemQty')
]

checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'
urlpatterns = [
    path('process/', views.process, name="process"),
    path("submit/", views.submit, name="submit")
]

transactions/urls.py
from django.urls import path
from . import views

app_name = "transactions"

urlpatterns = [
    path("history/", views.history_view, name="history"),
    path("checkout/", views.checkout, name="checkout"),
    path("add_transaction/", views.add_transaction, name="add")
]

wartec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth import logout
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls'), name='dashboard'),
    path('', include('cart.urls'), name='cart'),
    path('accounts/', include('allauth.urls')),
    path('accountLogin/', TemplateView.as_view(template_name='social_app/socialindex.html'), name='social_app'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("checkout/", include("checkout.urls"),name="checkout"),
    path('coupon/', include('coupon.urls'), name="coupon"),
    path("transactions/",include("transactions.urls"), name="transactions"),   
    path('djangoaccounts/', include('account.urls'), name='djangoaccounts'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.contrib.auth.models import User
from cart.models import Entry, Cart
from coupon.models import Coupon

# Create your models here.
class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ManyToManyField(Entry)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE, default= None, blank=True, null=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Transaction from user {self.user} using the coupon {self.coupon} on {self.date}"
    objects = models.Manager()

transactions/models.py
from django.db import models
from dashboard.models import Product
from coupon.models import Coupon

class Transaction(models.Model):
    @property
    def get_transaction(self):
        try:
            return self.barang.harga_barang * (100 - self.kupon.percentage) // 100
        except:
            return self.barang.harga_barang #Coupons are optional

    buyer_name = models.TextField(max_length=50)
    item = models.ForeignKey(Product, on_delete=models.PROTECT)
    total_transaction = get_transaction
    coupon = models.ForeignKey(Coupon, on_delete=models.PROTECT,null=True, blank=True) #Coupons are optional
    buy_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} @ {}".format(self.buyer_name, self.item, self.buy_date)
    objects = models.Manager()
    
        

    

checkout/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from cart.models import Cart
from .models import Checkout
from coupon.models import Coupon
from django.contrib.auth.decorators import login_required

@login_required(login_url='/accountLogin/')
def submit(request):
    kerown = Cart.objects.get(owner=request.user)
    ccart = kerown.items.all()
    checkout_list = {
        tb : tb.product.price * tb.quantity for tb in ccart #A list of items and their quantities in the checkout cart 
    }

    total_price = 0
    for price in checkout_list.values():
        total_price += price

    context = {
        "total_harga" : total_price,
        "checkout_list" : checkout_list.items(),
        "checkout_page" : True
    }
    return render(request, "checkout/transaksicepat.html", context)

@csrf_exempt
def process(request):
    kerown = Cart.objects.get(owner=request.user)
    ccart = kerown.items.all()
    if request.method == "POST" and request.is_ajax():
        for item_purchase in ccart:
            purchase_quantity = item_purchase.quantity
        coupon_name = request.POST["nama_kupon_dipilih"]
        chosen_coupon_instance = None
        if coupon_name != "None":
            chosen_coupon_instance = Coupon.objects.get(name = coupon_name)
        
        new_trans = Checkout.objects.create(
            user = request.user,
            coupon = chosen_coupon_instance
        )
        
        # Add item to checkout
        for tb in ccart:
            new_trans.item.add(tb)
            item_instance = tb.product
            item_instance.save()
        new_trans.save()

        # Emptying user's cart.
        kerown.items.clear()
        return JsonResponse({"status" : "success"})

transactions/views.py
from django.shortcuts import render, redirect
from .models import Transaction
from dashboard.models import Product
from coupon.models import Coupon
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from checkout.models import Checkout

def get_total_price(trans):
    total_price = 0
    for item_transaction in trans.item.all():
        total_price += item_transaction.product.price * item_transaction.quantity
    
    if trans.coupon != None:
        return int(total_price*(100-trans.coupon.percentage)/100)
    else:
        return total_price

@login_required(login_url='/accountLogin/')
def history_view(request):
    transaction_list = [
        (trans, get_total_price(trans), ", ".join(map(str,trans.item.all()))) for trans in Checkout.objects.filter(user = request.user).order_by("-date").all()
    ]
    context = {
        "transaction_list" : transaction_list
    }
    return render(request, "transactions/history.html", context)

@login_required(login_url='/accountLogin/')
def checkout(request):
    if request.method == "POST":
        # Checkout item details
        name = request.POST["name"]
        price = request.POST["price"]
        description = request.POST["description"]
        
        # To search for coupons
        try:
            coupon_name = request.POST["nama_kupon"] if request.POST["nama_kupon"] else ""
            coupon_percentage = request.POST["persentase_kupon"] if request.POST["persentase_kupon"] else 0
            coupon_list = Coupon.objects.filter(name__icontains = coupon_name)
            coupon_list = coupon_list.filter(percentage__gte = coupon_percentage)
            coupon_list = coupon_list.filter(expiry__gte = timezone.now(), min_price__lte = price) #Checking the expiry date and min price
        except:
            coupon_list = Coupon.objects.filter(expiry__gte = timezone.now(), min_price__lte = price)[:10]
            coupon_name = ""
            coupon_percentage = ""

        purchased_item = Product.objects.get(
            name = name,
            price = price,
            description = description
        )

        # To choose a coupon
        try:
            chosen_coupon = request.POST["kupon_terpilih"].split("---")
            chosen_coupon_name = chosen_coupon[0]
            chosen_coupon_percentage = chosen_coupon[1]
            price_after_discount = int(purchased_item.harga_barang * (100-float(chosen_coupon_percentage)) / 100)
        except:
            chosen_coupon_name = ""
            chosen_coupon_percentage = ""
            price_after_discount = None

        context = {
            "purchased_item" : purchased_item,
            "coupon_list" : coupon_list,
            "coupon_name" : coupon_name,
            "coupon_percentage" : coupon_percentage,
            "chosen_coupon_name" : chosen_coupon_name,
            "chosen_coupon_percentage" : chosen_coupon_percentage,
            "price_after_discount" : price_after_discount
        }

        return render(request, "transactions/checkout.html", context)
    else:
        return redirect("dashboard:landing")

def add_transaction(request):
    if request.method == "POST":
        # Details for items in checkout
        name = request.POST["name"]
        price = request.POST["price"]
        description = request.POST["description"]

        # Buyer details
        buyer_name = request.POST["first_name"] + " " + request.POST["last_name"]

        # Details for purchased item
        purchased_item = Product.objects.get(
            name = name,
            price = price,
            description = description
        )

        # Submit choosen coupon to the hidden form
        try:
            chosen_coupon_name = request.POST["kupon_terpilih_nama"]
            chosen_coupon_percentage = request.POST["kupon_terpilih_persentase"]
            chosen_coupon = Coupon.objects.get(name=chosen_coupon_name, percentage = chosen_coupon_percentage)
        except:
            chosen_coupon = None

        # Create new transaction
        new_transaction = Transaction.objects.create(
            name = buyer_name,
            price = purchased_item,
            kupon = chosen_coupon
        ).save()
        
        purchased_item.save()

    return redirect("dashboard:landing")

templates/transactions/checkout.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row h-100">
      <div class="col-lg-6 col-sm-12 p-5 d-flex justify-content-center align-items-center">
        <form action="{% url 'transactions:add' %}" method="POST">

            {% csrf_token %}
            <input type="hidden" value="{{purchased_item.name}}" name="name">
            <input type="hidden" value="{{purchased_item.price}}" name="price">
            <input type="hidden" value="{{purchased_item.description}}" name="description">
            <input type="hidden" value="{{chosen_coupon_name}}" name="chosen_coupon_name">
            <input type="hidden" value="{{chosen_coupon_percentage}}" name="chosen_coupon_percentage">
          
            <div class="w-100">
            <h4>First Name</h4>
            <input class="form-control" type="text" placeholder="First Name" name="first_name" required>
          </div>
          <div class="w-100 my-2">
            <h4>Last Name</h4>
            <input class="form-control" type="text" placeholder="Last Name" name="last_name" required>
          </div>
          <div>
            <h4>Item bought: {{purchased_item.name}}</h4>
          </div>
          
          <div class="mt-4">
              
            {% if price_after_discount != None %}
                <h3>Grand total:</h3>
                <h4>Rp. {{price_after_discount}}</h4>
            {% else %}
                <h3>Grand total:</h3>
                <h4>Rp. {{purchased_item.price}}</h4>
            {% endif %}
            <input type="submit" class="btn btn-main " value="Bayar Gan">
          </div>
        </form>
      </div>

      <div class="col-lg-6 col-sm-12 px-5 pt-lg-5">
        <form action="{% url 'transactions:checkout' %}" method="POST" class="d-flex justify-content-center align-items-center flex-column">
            {% csrf_token %}

            <input type="hidden" value="{{purchased_item.name}}" name="nama_barang">
            <input type="hidden" value="{{purchased_item.price}}" name="harga_barang">
            <input type="hidden" value="{{purchased_item.description}}" name="deskripsi_barang">
          
            <h2 class="mb-4">Save your money</h2>
          <div class="w-75 my-1">
            <h4>Coupon Name</h4>
            <input class="form-control" type="text" placeholder="Coupon Name" name="nama_kupon">
          </div>
          <div class="w-75 my-1">
            <h4>Coupon Percentage</h4>
            <input class="form-control" type="number" placeholder="Coupon Percentage" name="persentase_kupon">
          </div>
          <input type="submit" class="btn btn-main w-75" value="Cari Kupon">

          {% if chosen_coupon_name %}
        <p class="m-0 mt-2 p-0">You have picked the coupon "{{chosen_coupon_name}}"</p>
        <h4 class="m-0 p-0">for a discount of {{chosen_coupon_percentage}}%</h4>
        {% endif %}

        {% if coupon_name %}
        <p>Search for: {{coupon_name}}</p>
        {% endif %}
        
        {% if coupon_percentage %}
        <p>Over: {{coupon_percentage}}%</p>
        {% endif %}


        <p class="m-0 p-0 pt-3">Available Coupons:</p>
        <div class="row mt-3">
            {% for coupon in coupon_list %}
                <div class="col-4 d-flex justify-content-center align-items-center flex-column my-1">
                    <button type="submit" value="{{coupon.name}}---{{coupon.percentage}}" name="chosen_coupon"
                    class="bg-coupon text-light rounded-lg px-2 py-1 text-center d-flex justify-content-center align-items-center flex-column">
                        <p class="m-0 p-0">{{coupon.name}}</p>
                        <p class="m-0 p-0">{{coupon.percentage}}% Off</p>
                    </button>
                </div>
            {% endfor %}
          </div>

        </form>

        
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/transactions/history.html
{% extends 'base.html' %}
{% block content %}
    <div class="container p-2 d-flex justify-content-center align-items-center flex-column">
        {% for transaction in transaction_list %}
        <div class="w-75 p-3 my-2" id="transaction-card">
            <div class="row">
                <div class="col-lg-6 col-sm-12 d-flex justify-content-center align-items-start flex-column">
                    <h1 class="m-0 p-0">{{transaction.0.user.username}}</h1>
                    <p class="m-0 p-0">Item: {{transaction.2}}</p>
                </div>
                <div class="col-lg-6 col-sm-12 d-flex justify-content-center align-items-start flex-column">
                    <p class="m-0 p-0">{{transaction.0.date|date:"Y-m-d / G:i"}}</p>
                    <p class="m-0 p-0">
                        {% if transaction.0.coupon != None %} 
                            Coupon: {{transaction.0.coupon.name}} ({{transaction.0.coupon.percentage}}% off)
                        {% else %}
                            No coupon used
                        {% endif %}
                    </p>
                    <h2 class="m-0 p-0">Rp. {{transaction.1}}</h2>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}  